name: Caller Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define which environment to run'
        required: true
        default: 'test' 
        type: choice
        options:
        - test
        - prod

jobs:
  caller-job-local:
    uses: ./.github/workflows/callee.yml
    with:
      app_name: my-app
      env_deploy: ${{ inputs.environment }}

  caller-job-external:
    uses: ps-actions-sandbox/demo-called-workflow/.github/workflows/demo_called_workflow.yaml@main
    with:
      app_name: my-other-app
      env_deploy: ${{ inputs.environment }}
